### PR TITLE
Add asdf-deno to install instructions list

### LINKED ISSUE #80: Add asdf plugin to installation instruction list

### PR DESCRIPTION
**Pull request by imbsky**
Closes #80

### CODE REVIEW

**Comment by imbsky** [comment]
Context: #80

**Comment by kt3k** [comment]
@imbsky 
Thank you for the contribution. I have a question about asdf-plugin repository. Recently the repo has accepted another plugin as deno plugin in a PR https://github.com/asdf-vm/asdf-plugins/pull/104. Does this mean that [johnlayton/valdastreet](https://github.com/johnlayton/valdastreet) is the official plugin for asdf ecosystem?

**Comment by imbsky** [comment]
I'm also the maintainer/member of the `asdf-plugins` and `asdf-community`. In my opinion, the notion of official plugin doesn't quite fit for asdf version manager. Although I will update to `asdf-community/asdf-deno`, because We have a confident that `asdf-community/asdf-deno` is tested and checked well.

**Comment by imbsky** [comment]
`asdf-community/asdf-deno` is actually installed and run, tested with bats-core, and lint with shellcheck on GitHub Actions.

**Comment by imbsky** [comment]
https://github.com/asdf-community/asdf-deno/blob/master/.github/workflows/workflow.yml

**Comment by imbsky** [comment]
Well, the same thing (The fact that `asdf-plugins` is NOT an official plugin directory) I said is in the README for `asdf-plugins`...

**Comment by imbsky** [comment]
I updated plugin directory.

**Pull request merged**
