### PR TITLE
Restrict Set-ExecutionPolicy scope

### PR DESCRIPTION
**Pull request by mattcbaker**
Restrict the scope on the recommended fix for the Powershell execution error. The options for the -Scope flag are "LocalMachine" (default), "CurrentUser", "Process", "UserPolicy" or "MachinePolicy". "Process" is the only option that doesn't make a permanent change -- it **only** allows the install script to run in the current Powershell session.

More info on -Scope here https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.security/set-executionpolicy?view=powershell-7

### CODE REVIEW

**Comment by MarkTiedemann** [comment]
LGTM.

cc @ry

**Comment by MarkTiedemann** [comment]
With https://github.com/denoland/deno_install/issues/114, this PR would be obsolete (In fact, we could remove the whole "Known Issues" section).

**Comment by MarkTiedemann** [comment]
Since #133 has been merged, the known issue "Running scripts is disabled" does not exist anymore. So this PR can be closed.

**Comment by bartlomieju** [comment]
@mattcbaker thank you for the work and opening PR. As pointed by @MarkTiedemann this issue is no longer relevant, so closing without merge. Thank you for your contribution!

**Pull request closed without merging**
