### PR TITLE
fix IHTMLDocument2_write not exist

### LINKED ISSUE #35: does not contain a method named 'IHTMLDocument2_write'
```
PS C:\Users\zhang> iex (iwr https://deno.land/x/install/install.ps1)
iex : Method invocation failed because [System.__ComObject] does not contain a method named 'IHTMLDocument2_write'.
At line:1 char:1
+ iex (iwr https://deno.land/x/install/install.ps1)
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (IHTMLDocument2_write:String) [Invoke-Expression], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound,Microsoft.PowerShell.Commands.InvokeExpressionCommand
```

### PR DESCRIPTION
**Pull request by zhmushan**
fix #35

### CODE REVIEW

**Comment by ry** [comment]
cc @MarkTiedemann

**Comment by MarkTiedemann** [comment]
LGTM.

I'd even replace the old line instead of using the try-catch.

`$HTMLFile.write([System.Text.Encoding]::Unicode.GetBytes($Response.Content))` is much cleaner to me.

**Comment by zhmushan** [comment]
@MarkTiedemann
Done.

**Comment by zhmushan** [comment]
ci is red.
I think it caused by a different powershell version, because the test passed on my machine.
Maybe trycatch should be retained?

**Comment by MarkTiedemann** [comment]
I'd prefer to have an if-else based on the PowerShell version, or an if-else based on whether the IHTMLDocument2_write member exists on the ComObject. If we can't get that to work reliably, then try-catch.

**Comment by MarkTiedemann** [comment]
Perfect, thanks!

**Pull request merged**
