### PR TITLE
Updat the deno version to be installed with asdf

### PR DESCRIPTION
**Pull request by manuraj17**
Changes:
- In the README, update the deno version to be installed with asdf to 1.0.0

Although the change is trivial and not any sort of deal breaker, felt it's good to have the docs updated. I can update the whole doc if the version is available in every other installation source. I have only tried asdf, so I am not aware of other sources.

### CODE REVIEW

**Comment by MarkTiedemann** [comment]
The reason why you find `0.38.0` in the docs rather than `1.0.0` is that this is for installing a _specific version_ rather than the _latest version_ of Deno.

In general, I think it's fine to update in this section: https://github.com/denoland/deno_install#install-and-manage-multiple-versions

But this section https://github.com/denoland/deno_install#install-specific-version should not be updated.

**Comment by manuraj17** [comment]
@MarkTiedemann Ohkay. Gotcha. I have updated only the ASDF version. I will update the scoop version as well. I didn't want the document to give the feeling that it was outdated. Shall I update the PR with updating scoop version to point to 1.0.0?

**Comment by MarkTiedemann** [comment]
@manuraj17 Sure, sounds good to me. :)

Deno `1.0.0` is available for Scoop: https://github.com/ScoopInstaller/Main/blob/master/bucket/deno.json

**Comment by manuraj17** [comment]
@MarkTiedemann Ah okay cool! I was searching the scoop repo, I don't use that tool so was trying to find where it is. Let me update the PR and push.

**Comment by MarkTiedemann** [comment]
LGTM.

cc @ry

**Pull request merged**
